name: CMake (Windows + Ubuntu) with vcpkg

on:
  push:
    branches: [ Main, main ]
  pull_request:
    branches: [ Main, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        build_type: [ Release ]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install deps declared in vcpkg.json and expose VCPKG_ROOT + toolchain file
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
          vcpkgJsonGlob: '**/vcpkg.json'

      # Windows uses MSVC (cl) automatically. Ubuntu needs compilers explicitly.
      - name: Set compilers (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "CC=${{ matrix.c_compiler }}"  >> $GITHUB_ENV
          echo "CXX=${{ matrix.cpp_compiler }}" >> $GITHUB_ENV

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        shell: bash
        run: cmake --build build --config ${{ matrix.build_type }} -- -j 2

      - name: Test
        shell: bash
        run: ctest --test-dir build --output-on-failure -C ${{ matrix.build_type }}
